parametros:  
  Lx: 1200.0 #Dimension en X de pantalla 
  Ly: 720.0 #Dimension en Y de pantalla
  N: 200 # numero de particulas
  mu: 70  # media de masa
  sigma: 10 # varianza
  G: 0.04 # Constante gravitacional
  J: 0.40 # constante de proporcion para la masa/radio;;; radio proporcional a la raiz cubica de la masa
  dt1: 0.25 # hace referencia al step de tiempo usando en Force.